"""Domain models and exceptions."""

from stock_portfolio_auditor.domain.errors import (
    BrokerNotDetectedError,
    CoverageGapError,
    FormatNotSupportedError,
    ParserError,
    PeriodDetectionError,
    PriceProviderError,
    ReconciliationError,
    SPAError,
    StatementCorruptError,
    TickerResolutionError,
)
from stock_portfolio_auditor.domain.models import (
    AssetKind,
    CashBalance,
    CostBucket,
    Holding,
    IncomeBucket,
    OptionMeta,
    OptionType,
    Statement,
    Transaction,
    TransactionAction,
    quantize_decimal,
)

__all__ = [
    "AssetKind",
    "BrokerNotDetectedError",
    "CashBalance",
    "CostBucket",
    "CoverageGapError",
    "FormatNotSupportedError",
    "Holding",
    "IncomeBucket",
    "OptionMeta",
    "OptionType",
    "ParserError",
    "PeriodDetectionError",
    "PriceProviderError",
    "ReconciliationError",
    "SPAError",
    "Statement",
    "StatementCorruptError",
    "TickerResolutionError",
    "Transaction",
    "TransactionAction",
    "quantize_decimal",
]
